spring:
  thymeleaf:
    cache: false

  profiles:
    active: dev


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.htr.pojo
