spring:
  thymeleaf:
    mode: HTML

  profiles:
    active: dev

  resources:
    static-locations: classpath:/static/images, classpath:/static/css, classpath:/static/js, classpath:/static/lib



mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

