spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://34.105.241.17:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: bloglocal
    password: 804232452

logging:
  level:
    root: warn
    com.htr: info
  file:
    name: log/blog-pro.log
server:
  port: 8080

